import java.util.Date
import java.net.URI
import org.gradle.api.plugins.JavaBasePlugin
import org.gradle.api.tasks.bundling.Jar

plugins {
    java
    `maven-publish`
}

group = "no.nav.helse.xml"
version = "1.0.2"

subprojects {
    group = "no.nav.helse.xml"
    version = "1.0.2-13"

    apply(plugin = "java")
    apply(plugin = "maven-publish")

    repositories {
        mavenCentral()
        jcenter()
    }

    val jaxbBasicAntVersion = "1.11.1"
    val jaxbVersion = "2.3.0.1"
    val jaxbApiVersion = "2.1"
    val javaTimeAdapterVersion = "1.1.3"

    val xjc by configurations.creating

    dependencies {
        xjc("javax.xml.bind", "jaxb-api", jaxbApiVersion)
        xjc("com.sun.xml.bind", "jaxb-xjc", jaxbVersion)
        xjc("com.sun.xml.bind", "jaxb-impl", jaxbVersion)
        xjc("com.sun.xml.bind", "jaxb-core", jaxbVersion)
        xjc("org.jvnet.jaxb2_commons", "jaxb2-basics-ant", jaxbBasicAntVersion)
        xjc("com.migesok", "jaxb-java-time-adapters", javaTimeAdapterVersion)
        implementation("javax.xml.bind:jaxb-api:2.3.0")
        implementation("org.glassfish.jaxb:jaxb-runtime:2.3.2")
        implementation("com.migesok", "jaxb-java-time-adapters", javaTimeAdapterVersion)
    }

    configure<JavaPluginConvention> {
        sourceCompatibility = JavaVersion.VERSION_1_8
    }

    ext["xjbOutputDir"] = file("$buildDir/generated-sources/jaxb2")

    sourceSets["main"].java {
        srcDirs(ext["xjbOutputDir"] as File)
    }

    publishing {
        repositories {
            maven {
                url = uri("https://oss.sonatype.org/service/local/staging/deploy/maven2")
                this.credentials {
                    username = System.getenv("GH_PACKAGES_USERNAME")
                    password = System.getenv("GH_PACKAGES_PASSWORD")
                }
            }
        }
        publications {
            create<MavenPublication>("mavenJava") {
                from(components["java"])
                //artifact(tasks.getByName("sourcesJar"))
                pom {

                    name.set("SYFO XML beans")
                    description.set("A collection of XML beans")
                    url.set("https://github.com/navikt/syfo-xml-codegen")

                    licenses {
                        license {
                            name.set("MIT License")
                            url.set("https://opensource.org/licenses/MIT")
                        }
                    }

                    scm {
                        connection.set("scm:git:https://github.com/navikt/syfo-xml-codegen.git")
                        developerConnection.set("scm:git:https://github.com/navikt/syfo-xml-codegen.git")
                        url.set("https://github.com/navikt/syfo-xml-codegen")
                    }
                }
            }
        }
    }

    tasks {
        register("printVersion") {
            doLast {
                println(project.version)
            }
        }

        val generatePomPropertiesForJar by registering {
            val outputDir = file("$buildDir/pom-properties")
            outputDir.mkdirs()
            val outputFile = file("$outputDir/pom.properties")
            outputFile.writeText("""
#Generated by Gradle
#${Date()}
groupId=${project.group}
artifactId=${project.name}
version=${project.version}
""".trimIndent())
            outputs.file(outputFile)
        }

        val sourcesJar by registering(Jar::class) {
            classifier = "sources"
            from(sourceSets["main"].allSource)
            val generatePomFileForMavenJavaPublication = getByName("generatePomFileForMavenJavaPublication")
            dependsOn(generatePomPropertiesForJar, generatePomFileForMavenJavaPublication)

            into("META-INF/maven/${project.group}/${project.name}") {
                from(generatePomPropertiesForJar)
                from(generatePomFileForMavenJavaPublication) {
                    rename(".+", "pom.xml")
                }
            }
        }

        withType<Jar> {
            val generatePomFileForMavenJavaPublication = getByName("generatePomFileForMavenJavaPublication")
            dependsOn(generatePomPropertiesForJar, generatePomFileForMavenJavaPublication)

            into("META-INF/maven/${project.group}/${project.name}") {
                from(generatePomPropertiesForJar)
                from(generatePomFileForMavenJavaPublication) {
                    rename(".+", "pom.xml")
                }
            }
        }
    }
}
