rootProject.name = "syfo-xml-codegen"
include ("sm2013")
include ("legeerklaering")
include ("fellesformat")
include ("oppfolgingsplan")
include ("papirsykemelding")
include ("kontrollsystemblokk")
include ("xmlfellesformat")
include("dialogmelding")
include("base64container")
include("xmlfellesformat2")
