rootProject.name = "syfo-xml-codegen"
include ("sm2013")
include ("legeerklaering")
include ("fellesformat")
include ("infotrygd-foresp")
include ("oppfolgingsplan")
include ("papirsykemelding")
include ("kontrollsystemblokk")
include ("kith-hodemelding")
include ("xmlfellesformat")
include ("kith-apprec")
include ("tss-samhandler-data")
include("dialogmelding")
include("base64container")
include("xmlfellesformat2")
include("sykmelding-arbeidsgiver")
