name: Publish artifacts
on:
  push:
    branches:
      - master
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: test and build
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)" build
      - name: upload artifact
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)" publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
