name: Publish artifacts
on:
  release:
    types: [published]
env:
  NEW_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup java 11
        uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup gradle dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: test and build
        run: ./gradlew -Pversion=${{ env.NEW_VERSION }} build
      - name: upload artifact
        run: ./gradlew -Pversion=${{ env.NEW_VERSION }} publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
